{
 "title": "Raspbi Monitoring",
 "tags": [
  "speedtest",
  "ping",
  "node exporter",
  "raspberry",
  "d3vilh"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_thermal_zone_temp" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Server Uptime",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{} - node_boot_time_seconds{}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"idle\"}[30s])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes)) * 100)"
    }
   ]
  },
  {
   "title": "RootFS free",
   "type": "stat",
   "description": "Free space in / partition. \n<= 14.4Gb left - green.\n<= 10.4Gb left - yellow.\n<= 6.4Gb left - RED.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "Free GB" }
   ]
  },
  {
   "title": "Disk I/O Now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_io_now{device=\"mmcblk0\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_disk_io_now{device=\"mmcblk0p1\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_disk_io_now{device=\"mmcblk0p2\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk RW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_disk_written_bytes_total", "legendFormat": "{{device}}" },
    { "expr": "node_disk_read_bytes_total", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "Running" },
    { "expr": "node_procs_blocked", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "stat",
   "description": "Swap usage",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100)",
     "legendFormat": "swap usage"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"iowait\"}[1m])) * 100 <=100",
     "legendFormat": "{{iowait}}"
    }
   ]
  },
  {
   "title": "Traffic eth0",
   "type": "stat",
   "description": "The main metrics for are bandwidth usage which comes from the netdev module, and is covered by node_network_receive_bytes_total and node_network_transmit_bytes_total. Both bits per second.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Download Avg.",
   "type": "gauge",
   "description": "Average download speed by Speedtest.net",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Upload Avg.",
   "type": "gauge",
   "description": "Average upload speed by Speedtest.net",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Ping Latency Avg.",
   "type": "gauge",
   "description": "Average Ping latency by Speedtest.net",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "The main metrics for are bandwidth usage which comes from the netdev module, and is covered by node_network_receive_bytes_total and node_network_transmit_bytes_total. Both bits per second.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "{sensor=\"temp0\"}",
     "legendFormat": "Temp 0"
    },
    {
     "expr": "{sensor=\"temp1\"}",
     "legendFormat": "Temp 1"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"idle\"}[30s])) * 100",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  }
 ]
}