---
# Location where configuration files will be stored.
config_dir: '~'

# Porteiner configuration.
portainer_enable: true

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: Europe/Kiev
pihole_password: "gagaZush" #Change this password!

# OpenVPN configuration.
ovpn_enable: true
ovpnui_user: "admin"
ovpnui_password: "gagaZush" #Change this password!

# Raspi-monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin" #Is only used the first time Grafana starts up
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://www.apple.com/;apple.com
  - https://github.com/;github
  - https://reddit.com/;reddit

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: true 
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  # AirGradient FW example ./files/AirGradient-DIY.ino 
  - id: livingroom
    ip: "192.168.88.6"
    port: 9926

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "gagaZush"
