---
- hosts: raspberry_gateway
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file)
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml
        - advanced.config.yml

    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Setup Portainer
      ansible.builtin.import_tasks: tasks/portainer.yml
      when: portainer_enable

    - name: Setup OpenVPN Client
      ansible.builtin.import_tasks: tasks/openvpn-client.yml
      when: ovpn_client_enable

    - name: Setup OpenVPN Server
      ansible.builtin.import_tasks: tasks/openvpn-server.yml
      when: ovpn_server_enable

    - name: Setup Unbound DNS
      ansible.builtin.import_tasks: tasks/unbound-dns.yml
      when: unbound_dns_enable

    - name: Setup Pi Hole
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when: pihole_enable

    - name: Setup Technitium DNS Server
      ansible.builtin.import_tasks: tasks/tech-dns.yml
      when: tech_dns_enable

    - name: Setup WireGuard Server
      ansible.builtin.import_tasks: tasks/wireguard.yml
      when: wireguard_server_enable

    - name: Setup qBitTorrent
      ansible.builtin.import_tasks: tasks/qbittorrent.yml
      when: qbittorrent_enable

    - name: Setup Raspi Monitoring
      ansible.builtin.import_tasks: tasks/raspi-monitoring.yml
      when: monitoring_enable

    - name: Setup Shelly Plug Monitoring
      ansible.builtin.import_tasks: tasks/shelly-plug.yml
      when: shelly_plug_monitoring_enable

#  TESTING GLUETUN
#  DONT USE ON PROD!!!!

    - name: Setup Gluetun Server
      ansible.builtin.import_tasks: tasks/gluetun.yml
      when: gluetun_vpnclient_enable