{
 "title": "Raspberry Monitoring",
 "tags": [
  "speedtest",
  "ping",
  "node exporter",
  "raspberry",
  "d3vilh"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_thermal_zone_temp" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Server Uptime",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{} - node_boot_time_seconds{}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"idle\"}[30s])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes)) * 100)"
    }
   ]
  },
  {
   "title": "RootFS free",
   "type": "stat",
   "description": "Free space in / partition. \n<= 14.4Gb left - green.\n<= 10.4Gb left - yellow.\n<= 6.4Gb left - RED.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "Free GB" }
   ]
  },
  {
   "title": "Disk I/O Now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_io_now{device=\"mmcblk0\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_disk_io_now{device=\"mmcblk0p1\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_disk_io_now{device=\"mmcblk0p2\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk RW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_disk_written_bytes_total", "legendFormat": "{{device}}" },
    { "expr": "node_disk_read_bytes_total", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "Running" },
    { "expr": "node_procs_blocked", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "stat",
   "description": "Swap usage",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100)",
     "legendFormat": "swap usage"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"iowait\"}[1m])) * 100 <=100",
     "legendFormat": "{{iowait}}"
    }
   ]
  },
  {
   "title": "File system status",
   "type": "bargauge",
   "description": "File system usage",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"} - node_filesystem_avail_bytes{device=\"/dev/root\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internet ISP monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Download Avg.",
   "type": "gauge",
   "description": "Average download speed by Speedtest.net",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second"
    }
   ]
  },
  {
   "title": "Upload Avg.",
   "type": "gauge",
   "description": "Average upload speed by Speedtest.net",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Ping Latency Avg.",
   "type": "gauge",
   "description": "Average Ping latency by Speedtest.net",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "timeseries",
   "description": "The main metrics for are bandwidth usage which comes from the netdev module, and is covered by node_network_receive_bytes_total and node_network_transmit_bytes_total. Both bits per second.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total[1m])",
     "legendFormat": "{{device}} receive packets"
    },
    {
     "expr": "rate(node_network_transmit_packets_total[1m])",
     "legendFormat": "{{device}} transmit packets"
    },
    {
     "expr": "rate(node_network_receive_multicast_total[1m])",
     "legendFormat": "{{device}} multicast"
    },
    {
     "expr": "rate(node_network_receive_drop_total[1m])",
     "legendFormat": "{{device}} receive drop"
    },
    {
     "expr": "rate(node_network_transmit_drop_total[1m])",
     "legendFormat": "{{device}} transmit drop"
    },
    {
     "expr": "rate(node_network_transmit_errs_total[1m])",
     "legendFormat": "{{device}} transmit error"
    },
    {
     "expr": "rate(node_network_receive_errs_total{}[1m])",
     "legendFormat": "{{device}} receive error"
    }
   ]
  },
  { "title": "Hardware Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "description": "Officially the Raspberry Pi’s processor is built to withstand temperatures from -40°C to 85°C.\n\nCPU Starts to throttle if temp raises higher that 80°C.\n\nAnything below 50°C is normal computing temperature.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temp 0"
    },
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp1\"}",
     "legendFormat": "Temp 1"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"idle\"}[30s])) * 100",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk operations",
   "type": "timeseries",
   "description": "Disk operations and FS free size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    { "expr": "node_filesystem_avail_bytes{}", "legendFormat": "{{mountpoint}} free" },
    { "expr": "node_disk_io_now", "legendFormat": "{{device}} io" },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{device}} read"
    }
   ]
  },
  { "title": "Power Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_voltage", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Power state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_power_state", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "rpi_voltage", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Power State",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "targets": [
    { "expr": "rpi_power_state", "legendFormat": "{{id}}" }
   ]
  },
  { "title": "Clocks Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Clocks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_clock_rate_measured_hz", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Clocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "rpi_clock_rate_measured_hz", "legendFormat": "{{id}}" }
   ]
  },
  { "title": "Containers Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Number of running containers",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU per container",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])) by (name) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[5m])) by (id)",
     "legendFormat": "RECIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[5m])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rate(container_network_transmit_bytes_total{name!=\"\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS memory usage per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers FS I/O current",
   "type": "timeseries",
   "description": "container_fs_io_current",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "container_fs_io_current{name!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container FS read total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}