---
- name: Create Gluetun folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/gluetun"
    state: directory
    mode: 0755
  become: false

- name: Synchronize Gluetun directory.
  ansible.posix.synchronize:
    src: gluetun
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  become: false

- name: Pull latest Gluetun Docker image
  community.general.docker_image:
    source: pull
    name: qmcgaw/gluetun
    tag: latest
  become: false

- name: Copy Gluetun docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/gluetun/{{ item.dest }}"
    mode: 0640
  loop:
    - src: gluetun-docker-compose.yml.j2
      dest: docker-compose.yml
  become: false
  notify: Restart gluetun

- name: Ensure Gluetun is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/gluetun/"
    build: false
  become: false
  environment:
    DOCKER_CLIENT_TIMEOUT: '180'
    COMPOSE_HTTP_TIMEOUT: '180'
