---
- name: Create OpenVPN folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/openvpn"
    state: directory
    mode: 0755
  become: false

- name: Synchronize openvpn directory.
  ansible.posix.synchronize:
    src: openvpn
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  become: false

- name: Copy OpenVPN docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/openvpn/{{ item.dest }}"
    mode: 0740
  loop:
    - src: openvpn-docker-compose.yml.j2
      dest: docker-compose.yml
    - src: openvpn-docker-entrypoint.sh.j2
      dest: openvpn-docker/docker-entrypoint.sh
    - src: openvpn_client.conf.j2
      dest: config/client.conf
  become: false
  notify: Restart openvpn

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure OpenVPN is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/openvpn/"
    build: false
  become: false
